platform :ios, '14.1'
use_frameworks!

def base_pods
 pod 'ZcashLightClientKit', :git => 'https://github.com/Meshbits/ZcashLightClientKit.git', :tag => 'v12-beta-5.3'
  # pod 'ZcashLightClientKit', :path => '../../ZcashLightClientKit'
  pod 'gRPC-Swift', '~> 1.0.0'
  # pod 'ZcashLightClientKit', :git => 'https://github.com/zcash/ZcashLightClientKit.git', :tag => '0.12.0-beta.5'
  pod 'KeychainSwift', '~> 19.0.0'
  pod 'MnemonicSwift' #, :git => 'https://github.com/zcash-hackworks/MnemonicSwift.git', :branch => 'master'
  pod 'lottie-ios'
  pod 'CombineUrlSessionDownloader'
  pod 'BottomSheet', :git => 'https://github.com/weitieda/bottom-sheet.git'
  pod 'AlertToast'
  pod 'SecureDefaults',:git => 'https://github.com/Meshbits/SecureDefaults.git'
end

inhibit_all_warnings!

target 'ECC-Wallet-no-logging' do
  base_pods
end

target 'ECC-Wallet' do 
  base_pods
  pod 'Mixpanel-swift'
#  pod 'Bugsnag'
  pod 'zealous-logger', :git => 'https://github.com/zcash-hackworks/zealous-logger', :branch => 'master'
  
end

target 'ECC-Wallet-Testnet' do
  base_pods
  pod 'Mixpanel-swift'
#  pod 'Bugsnag'
  pod 'zealous-logger', :git => 'https://github.com/zcash-hackworks/zealous-logger', :branch => 'master'
  
end

target 'ECC-WalletTests' do
   base_pods
  inherit! :search_paths
end

 target 'ECC-WalletUITests' do
   inherit! :search_paths
   
 end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      if target.name == 'ZcashLightClientKit'
         config.build_settings['ZCASH_NETWORK_ENVIRONMENT'] = "MAINNET"
      end

      config.build_settings['ENABLE_BITCODE'] = 'NO'
    end
  end
end
